# ---- builder: add providers + run kc build ----
FROM quay.io/keycloak/keycloak:26.1 AS builder

COPY --chown=keycloak:keycloak ./kc-disable-user-registration/target/*.jar /opt/keycloak/providers/

# IMPORTANT: build after providers are present
RUN /opt/keycloak/bin/kc.sh build

# ---- runtime ----
FROM quay.io/keycloak/keycloak:26.1

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
